name: Build LaTeX document
on: 
  push:
    paths:
      - '**.tex'
      - '**.bib'
  pull_request:
    paths:
      - '**.tex'
      - '**.bib'
  workflow_dispatch:

jobs:
  # see https://github.com/wtfjoke/setup-tectonic?tab=readme-ov-file#with-biber
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Tectonic cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-cache-${{ hashFiles('**/*.tex') }}
          restore-keys: ${{ runner.os }}-tectonic-cache-

      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: 'latest'

      - name: Build LaTeX document
        run: tectonic deliverable.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: deliverable.pdf
          if-no-files-found: error
