name: Build LaTeX document
on: 
  push:
    paths:
      - '**.tex'
      - '**.bib'
  pull_request:
    paths:
      - '**.tex'
      - '**.bib'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build LaTeX document
        run: tectonic deliverable.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: deliverable.pdf
          if-no-files-found: error

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: deliverable.pdf
          tag_name: v${{ github.run_number }}
          name: Build ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
